export const SCALE_TYPE = {
  EMOJI_SCALE_1_7: 'EMOJI_SCALE_1_7',
  CONTINUOUS_SLIDER_0_10: 'CONTINUOUS_SLIDER_0_10',
  HOUR_CHIPS: 'HOUR_CHIPS',
  TOGGLE_YES_NO: 'TOGGLE_YES_NO',
  RPE_BANDS_0_10: 'RPE_BANDS_0_10',
  NUMBER_INPUT: 'NUMBER_INPUT',
  TEXT_INPUT: 'TEXT_INPUT',
  OPTIONAL_GROUP: 'OPTIONAL_GROUP',
};

const EMOJI_BY_POSITION_WORST_TO_BEST = ['😣', '🙁', '😕', '😐', '🙂', '😊', '🤩'];

export const HOUR_CHIP_MIDPOINT = {
  '< 4h': 3.5,
  '4-5h': 4.5,
  '5-6h': 5.5,
  '6-7h': 6.5,
  '7-8h': 7.5,
  '8-9h': 8.5,
  '> 9h': 9.5,
};

export const CHECKIN_QUESTIONS = [
  {
    id: 'qualidade_sono',
    order: 1,
    implemented: true,
    type: SCALE_TYPE.EMOJI_SCALE_1_7,
    question: 'Como foi seu sono essa noite?',
    microcopy: 'Pense na noite inteira, não só na hora que o despertador tocou.',
    labels: [
      { displayPosition: 1, formulaValue: 1, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[0], text: 'Muito ruim' },
      { displayPosition: 2, formulaValue: 2, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[1], text: 'Ruim' },
      { displayPosition: 3, formulaValue: 3, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[2], text: 'Meio fraca' },
      { displayPosition: 4, formulaValue: 4, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[3], text: 'Regular' },
      { displayPosition: 5, formulaValue: 5, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[4], text: 'Boa' },
      { displayPosition: 6, formulaValue: 6, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[5], text: 'Muito boa' },
      { displayPosition: 7, formulaValue: 7, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[6], text: 'Excelente' },
    ],
  },
  {
    id: 'duracao_sono_horas',
    order: 2,
    implemented: true,
    type: SCALE_TYPE.HOUR_CHIPS,
    question: 'Quantas horas você dormiu, no total?',
    microcopy: 'Vale soneca gigante de manhã também — soma tudo.',
    chips: ['< 4h', '4-5h', '5-6h', '6-7h', '7-8h', '8-9h', '> 9h'],
  },
  {
    id: 'fadiga_geral',
    order: 3,
    implemented: true,
    type: SCALE_TYPE.EMOJI_SCALE_1_7,
    question: 'Qual seu nível de cansaço geral agora?',
    microcopy: 'Não é sono — é a bateria do corpo mesmo, antes de qualquer café.',
    labels: [
      { displayPosition: 1, formulaValue: 1, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[0], text: 'Exaustão total' },
      { displayPosition: 2, formulaValue: 2, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[1], text: 'Muito alta' },
      { displayPosition: 3, formulaValue: 3, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[2], text: 'Alta' },
      { displayPosition: 4, formulaValue: 4, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[3], text: 'Moderada' },
      { displayPosition: 5, formulaValue: 5, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[4], text: 'Leve' },
      { displayPosition: 6, formulaValue: 6, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[5], text: 'Muito leve' },
      { displayPosition: 7, formulaValue: 7, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[6], text: 'Nenhuma' },
    ],
  },
  {
    id: 'estresse_percebido',
    order: 4,
    implemented: true,
    type: SCALE_TYPE.EMOJI_SCALE_1_7,
    question: 'E o estresse? Como está a cabeça hoje?',
    microcopy: 'Treino, trabalho, trânsito, grupo de família no WhatsApp — tudo conta.',
    labels: [
      { displayPosition: 1, formulaValue: 1, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[0], text: 'Extremo' },
      { displayPosition: 2, formulaValue: 2, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[1], text: 'Muito alto' },
      { displayPosition: 3, formulaValue: 3, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[2], text: 'Alto' },
      { displayPosition: 4, formulaValue: 4, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[3], text: 'Moderado' },
      { displayPosition: 5, formulaValue: 5, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[4], text: 'Leve' },
      { displayPosition: 6, formulaValue: 6, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[5], text: 'Muito leve' },
      { displayPosition: 7, formulaValue: 7, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[6], text: 'Nenhum' },
    ],
  },
  {
    id: 'humor_disposicao',
    order: 5,
    implemented: true,
    type: SCALE_TYPE.EMOJI_SCALE_1_7,
    question: 'Como está seu humor e disposição hoje?',
    microcopy: 'Vale sinceridade — ninguém aqui vai contar pro seu treinador.',
    labels: [
      { displayPosition: 1, formulaValue: 1, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[0], text: 'Péssimo' },
      { displayPosition: 2, formulaValue: 2, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[1], text: 'Muito ruim' },
      { displayPosition: 3, formulaValue: 3, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[2], text: 'Ruim' },
      { displayPosition: 4, formulaValue: 4, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[3], text: 'Neutro' },
      { displayPosition: 5, formulaValue: 5, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[4], text: 'Bom' },
      { displayPosition: 6, formulaValue: 6, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[5], text: 'Muito bom' },
      { displayPosition: 7, formulaValue: 7, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[6], text: 'Ótimo' },
    ],
  },
  {
    id: 'dor_muscular',
    order: 6,
    implemented: true,
    type: SCALE_TYPE.EMOJI_SCALE_1_7,
    question: 'Quanta dor muscular você sente hoje?',
    microcopy: 'Aquela dorzinha de treino conta — seja honesto com a escala.',
    labels: [
      { displayPosition: 1, formulaValue: 1, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[0], text: 'Extrema' },
      { displayPosition: 2, formulaValue: 2, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[1], text: 'Muito alta' },
      { displayPosition: 3, formulaValue: 3, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[2], text: 'Alta' },
      { displayPosition: 4, formulaValue: 4, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[3], text: 'Moderada' },
      { displayPosition: 5, formulaValue: 5, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[4], text: 'Leve' },
      { displayPosition: 6, formulaValue: 6, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[5], text: 'Muito leve' },
      { displayPosition: 7, formulaValue: 7, emoji: EMOJI_BY_POSITION_WORST_TO_BEST[6], text: 'Nenhuma' },
    ],
  },
  {
    id: 'prontidao_percebida',
    order: 7,
    implemented: true,
    type: SCALE_TYPE.CONTINUOUS_SLIDER_0_10,
    question: 'Considerando tudo, o quanto você se sente pronto pra treinar hoje?',
    microcopy: 'Essa é a pergunta que resume todas as outras. Confie no seu instinto.',
    anchors: { 0: 'Nada pronto', 5: 'Mais ou menos', 10: 'Totalmente pronto' },
  },
  {
    id: 'treinou_ontem',
    order: 8,
    implemented: true,
    type: SCALE_TYPE.TOGGLE_YES_NO,
    question: 'Você treinou ontem?',
    conditional: true,
  },
  {
    id: 'rpe_treino_anterior',
    order: 9,
    implemented: true,
    type: SCALE_TYPE.RPE_BANDS_0_10,
    question: 'Numa escala de 0 a 10, quão puxado foi o treino de ontem?',
    microcopy: 'Pense no esforço geral da sessão inteira.',
    conditional: true,
    dependsOn: { field: 'treinou_ontem', equals: true },
    bands: [
      { value: 0, label: 'Nada' },
      { value: 2, label: 'Muito leve' },
      { value: 4, label: 'Leve a moderado' },
      { value: 6, label: 'Um tanto puxado' },
      { value: 8, label: 'Puxado' },
      { value: 9, label: 'Muito puxado' },
      { value: 10, label: 'Máximo' },
    ],
  },
  {
    id: 'duracao_treino_anterior_min',
    order: 10,
    implemented: true,
    type: SCALE_TYPE.NUMBER_INPUT,
    question: 'Quanto tempo durou o treino de ontem (em minutos)?',
    microcopy: 'Do aquecimento ao alongamento final.',
    conditional: true,
    dependsOn: { field: 'treinou_ontem', equals: true },
  },
  {
    id: 'opcionais',
    order: 11,
    implemented: true,
    type: SCALE_TYPE.OPTIONAL_GROUP,
    question: 'Dados opcionais',
    fields: ['hrv_ms', 'fc_repouso_bpm', 'nota_livre'],
  },
];

export const CONFIRMATION_MESSAGES = [
  'Check-in feito! Seus dados já estão trabalhando enquanto você aquece.',
  'Recebido! Agora é só treinar — a análise é com a gente.',
  'Boa! Check-in registrado.',
  'Prontinho — check-in salvo.',
];
